### ISSUE TITLE
nagios in LX zone has problems to connect to it's own socket.

### ISSUE THREAD

**Issue by h0lzi** [joyent/illumos-joyent#128]
Did some experiments with nagios. Some worker process are defunct.
Problem here seem to be the number of workers:

/etc/nagios/nagios.cfg:
> Normally worker count is dynamically allocated based on 1.5 * number of cpu's
with a minimum of 4 workers.  This value will override the defaults
check_workers=3
>

I'm able to start 6 workers. All after that are defunct.
Having more then 6 workers is not hard if you don't tune the setting.
Others reported they where able to start more worker threads
Seems to depend on zone config.
My config:
` ],
  "max_physical_memory": 1024,
  "max_swap": 1024,
`
got 2 cpus on this smartos instance

Some strace show problems to connect to a socket. After that that process is defunct:

strace -e connect -f /usr/sbin/nagios /etc/nagios/nagios.cfg

...

[pid  4480] connect(3, {sa_family=AF_LOCAL, sun_path="/var/spool/nagios/cmd/nagios.qh"}, 33) = -1 ECONNREFUSED (Connection refused)
Failed to connect to query socket '/var/spool/nagios/cmd/nagios.qh': connect() failed: Connection refused

...

this also seems to be a timing thing. At least for me. Sometimes with strace (and the more output you enable) all processes are able to connect to this socket.

**Comment by rzezeski** [comment]
Sorry, I've never used nagios before: what version are you running? Also, what lx image are you using?

I tried nagios3 on ubuntu 14.04 but it didn't recognize the `check_workers` config.

**Comment by h0lzi** [comment]
Ups sorry forgot those information.


zone:
>{
  "brand": "lx",
  "image_uuid": "07b33b7a-27a3-11e6-816f-df7d94eea009",
  "kernel_version": "3.13.0",
  "autoboot": false,
  "alias": "testlxc",
  "hostname": "testlxc",
  "dns_domain": ".....",
  "resolvers": [
    "......"
  ],
  "max_physical_memory": 1024,
  "max_swap": 1024,
  "nics": [
    {
      "nic_tag": "admin",
      "ip": "....",
      "netmask": ".....",
      "gateway": "....",
      "primary": true
    }
  ]
}
>

> yum install epel-release
yum install nagios*
/usr/sbin/nagios /etc/nagios/nagios.cfg
>

**Comment by rzezeski** [comment]
This is a bug in nagios 4.0.8. The solution is to upgrade to the 4.1.x series or build your own with the correct patch applied. Full report below.

http://tracker.nagios.org/view.php?id=667

Turns out nagios 4.0.8 has a hardcoded listen backlog of 3 (which gets turned into 5 because of logic in [socket_listen](https://github.com/joyent/illumos-joyent/blob/master/usr/src/uts/common/fs/sockfs/sockcommon.c#L188-L202)). So the first 6 connect requests make it through (0 thru 5) but subsequent requests get `ECONNREFUSED` because we are dealing with an `AF_UNIX` socket.

The reason you can sometimes get more than 6 is because of the async nature of the connection requests. If you slow things down in the right place then more connections can get through. For example, I was able to get 8 successful connections several times by making use of the dtrace `chill()` action. But this is NOT a solution, just a demonstration that timing can vary the number of connections. The real fix was made to the nagios code itself.

```
# dtrace -wn 'fbt::lx_connect:entry /execname == "nagios"/ { printf("chill"); chill(45000000); }'
```
