### ISSUE TITLE
uname -p returns i386 on a 64bit CPU

### ISSUE THREAD

**Issue by taylorjonl** [joyent/illumos-joyent#91]
If you run `uname -p` the output is "i386" on a 64bit machine.  Linux returns x86_64 and FreeBSD returns amd64.  Returning i386 makes builds that use cmake that depend on 64 bit builds difficult, e.g. coreclr will not build because it requires 64 bits.

**Comment by jclulow** [comment]
It's unlikely that we're going to be able to change the output of `uname -p`, as this could conceivably break a bunch of scripts and operators that depend on the current behaviour.

The [isainfo(1)](http://illumos.org/man/1/isainfo) command is probably the best way that we have to determine if the execution of 64-bit programs is supported on the running system.

**Comment by jperkin** [comment]
It's likely they are simply using the wrong CMake constructs, i.e. checking for hardcoded strings rather than e.g. CMAKE_SIZEOF_VOID_P which is what I've seen a number of CMake projects use.  There should be plenty of examples of working 64-bit CMake packages in pkgsrc to copy from (otherwise we'd see a huge number of failures in our 64-bit builds).

**Comment by taylorjonl** [comment]
I should have commented sooner, I got the build working by adding this section:

    if(CMAKE_SYSTEM_NAME STREQUAL SunOS)
        set(CLR_CMAKE_PLATFORM_UNIX 1)
        EXECUTE_PROCESS(
          COMMAND isainfo -n
          OUTPUT_VARIABLE SUNOS_NATIVE_INSTRUCTION_SET
          )
       if(SUNOS_NATIVE_INSTRUCTION_SET MATCHES "amd64")
           set(CLR_CMAKE_PLATFORM_UNIX_TARGET_AMD64 1)
           set(CMAKE_SYSTEM_PROCESSOR "amd64")
       else()
            clr_unknown_arch()
        endif()
        set(CLR_CMAKE_PLATFORM_SUNOS 1)
    endif(CMAKE_SYSTEM_NAME STREQUAL SunOS)

The CMAKE_SYSTEM_PROCESSOR variable is what this project is using and it uses `uname -p` to populate it.  Not sure if the above is the cleanest but this variable was used in a lot of places so this was the simplest way to accomplish my goal.

Is there a place that I can find out what `isainfo -n` returns for various processors?

I am going to close this comment.

**Comment by jperkin** [comment]
I'd recommend against this approach.  It's better to target the compiler (using e.g. the CMAKE_SIZEOF_VOID_P macro I mentioned earlier) rather than the host architecture, so that you can support both 32-bit and 64-bit binaries.  SmartOS kernel is only ever 64-bit, so the isainfo approach will mean you can only build 64-bit binaries.  This may not matter for your use-case, but it's not something we could integrate into pkgsrc where we need multi-architecture support.

**Comment by taylorjonl** [comment]
Point taken, I will have to find out how/why the rest of the build process requires the CMAKE_SYSTEM_PROCESSOR to be x86_64 or amd64.  For the time being at least I got past the configure stage and onto the compile stage.

When you mention integrating it into pkgsrc, since SmartOS is always 64-bit are you speaking of getting the changes merged upstream into jsonn/pkgsrc?  If so what architectures need to be supported for that to occur?

In the end it will be a long time before this package is ready for pkgsrc.  The porting effort will take more interest from others with more expertise than me when it comes to cross platform C/C++ development, I am a C# developer trying to figure out how all this stuff works.

**Comment by jperkin** [comment]
Yes, I'd like to eventually upstream this work into pkgsrc so that it can be made available to all SmartOS users.  There are no specific rules about what architectures must be supported before a package is imported, but it's something I'd like to resolve beforehand anyway, as undoubtedly the first complaints will be that users cannot install the package when using the 32-bit base images.

As you say there is likely to be a lot more work involved before we get to that point, but it'd be great to remove any barriers to integration along the way.  Thanks for working on this!

**Comment by am11** [comment]
Problem is that CMake itself relies on `uname -p`  and friends to assign the value of `CMAKE_HOST_SYSTEM_PROCESSOR` and `CMAKE_SYSTEM_PROCESSOR` _before_ invoking the user scripts.

I have filed https://gitlab.kitware.com/cmake/cmake/issues/20333 upstream based on the discussion above; to prefer `isainfo` when available.
